# CIS Windows Server 2025 Standalone - Section 17: Advanced Audit Policy Configuration
# This file contains all Advanced Audit Policy Configuration rules

$Global:Rules += @(
    # 17.1 Account Logon
    @{
        Id = "17.1.1"
        Title = "Ensure 'Audit Credential Validation' is set to 'Success and Failure'"
        Section = "17.1 Account Logon"
        Profile = "Level1"
        Type = "AuditPolicy"
        Subcategory = "Credential Validation"
        Expected = "Success and Failure"
        Description = "This policy setting allows you to audit the credentials that are submitted during a user account logon request."
        Impact = "If no audit settings are configured, or if audit settings are too lax on the computers in your organization, security incidents might not be detected or not enough evidence will be available for network forensic analysis after security incidents occur."
        Remediation = "Navigate to Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\Account Logon\Audit Credential Validation and set it to Success and Failure."
    },
    
    # 17.2 Account Management
    @{
        Id = "17.2.1"
        Title = "Ensure 'Audit Application Group Management' is set to 'Success and Failure'"
        Section = "17.2 Account Management"
        Profile = "Level1"
        Type = "AuditPolicy"
        Subcategory = "Application Group Management"
        Expected = "Success and Failure"
        Description = "This policy setting allows you to audit events generated by changes to application groups such as the following: Application group is created, changed, or deleted; Member is added or removed from an application group; Application group is renamed, disabled, or enabled; Application group password is set or changed."
        Impact = "If no audit settings are configured, or if audit settings are too lax on the computers in your organization, security incidents might not be detected or not enough evidence will be available for network forensic analysis after security incidents occur."
        Remediation = "Navigate to Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\Account Management\Audit Application Group Management and set it to Success and Failure."
    },
    @{
        Id = "17.2.2"
        Title = "Ensure 'Audit Security Group Management' is set to include 'Success'"
        Section = "17.2 Account Management"
        Profile = "Level1"
        Type = "AuditPolicy"
        Subcategory = "Security Group Management"
        Expected = "Success"
        Description = "This policy setting allows you to audit events generated by changes to security groups such as the following: Security group is created, changed, or deleted; Member is added or removed from a security group; Security group type is changed."
        Impact = "If no audit settings are configured, or if audit settings are too lax on the computers in your organization, security incidents might not be detected or not enough evidence will be available for network forensic analysis after security incidents occur."
        Remediation = "Navigate to Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\Account Management\Audit Security Group Management and set it to include Success."
    },
    @{
        Id = "17.2.3"
        Title = "Ensure 'Audit User Account Management' is set to 'Success and Failure'"
        Section = "17.2 Account Management"
        Profile = "Level1"
        Type = "AuditPolicy"
        Subcategory = "User Account Management"
        Expected = "Success and Failure"
        Description = "This policy setting allows you to audit changes to user accounts. Events include the following: User account is created, changed, deleted; User account is renamed, disabled, or enabled; A password is set or changed."
        Impact = "If no audit settings are configured, or if audit settings are too lax on the computers in your organization, security incidents might not be detected or not enough evidence will be available for network forensic analysis after security incidents occur."
        Remediation = "Navigate to Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\Account Management\Audit User Account Management and set it to Success and Failure."
    },
    
    # 17.3 Detailed Tracking
    @{
        Id = "17.3.1"
        Title = "Ensure 'Audit PNP Activity' is set to include 'Success'"
        Section = "17.3 Detailed Tracking"
        Profile = "Level1"
        Type = "AuditPolicy"
        Subcategory = "PNP Activity"
        Expected = "Success"
        Description = "This policy setting allows you to audit when plug and play detects an external device."
        Impact = "If no audit settings are configured, or if audit settings are too lax on the computers in your organization, security incidents might not be detected or not enough evidence will be available for network forensic analysis after security incidents occur."
        Remediation = "Navigate to Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\Detailed Tracking\Audit PNP Activity and set it to include Success."
    },
    @{
        Id = "17.3.2"
        Title = "Ensure 'Audit Process Creation' is set to include 'Success'"
        Section = "17.3 Detailed Tracking"
        Profile = "Level1"
        Type = "AuditPolicy"
        Subcategory = "Process Creation"
        Expected = "Success"
        Description = "This policy setting allows you to audit events generated by the creation of a process and the name of the program or user that created it."
        Impact = "If no audit settings are configured, or if audit settings are too lax on the computers in your organization, security incidents might not be detected or not enough evidence will be available for network forensic analysis after security incidents occur."
        Remediation = "Navigate to Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\Detailed Tracking\Audit Process Creation and set it to include Success."
    },
    
    # 17.5 Logon/Logoff
    @{
        Id = "17.5.1"
        Title = "Ensure 'Audit Account Lockout' is set to include 'Failure'"
        Section = "17.5 Logon/Logoff"
        Profile = "Level1"
        Type = "AuditPolicy"
        Subcategory = "Account Lockout"
        Expected = "Failure"
        Description = "This policy setting allows you to audit when a user account is locked out as a result of too many failed logon attempts."
        Impact = "If no audit settings are configured, or if audit settings are too lax on the computers in your organization, security incidents might not be detected or not enough evidence will be available for network forensic analysis after security incidents occur."
        Remediation = "Navigate to Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\Logon/Logoff\Audit Account Lockout and set it to include Failure."
    },
    @{
        Id = "17.5.2"
        Title = "Ensure 'Audit Group Membership' is set to include 'Success'"
        Section = "17.5 Logon/Logoff"
        Profile = "Level1"
        Type = "AuditPolicy"
        Subcategory = "Group Membership"
        Expected = "Success"
        Description = "This policy setting allows you to audit the group membership information in the user's logon token. Events in this subcategory are generated on the computer on which a logon session is created."
        Impact = "If no audit settings are configured, or if audit settings are too lax on the computers in your organization, security incidents might not be detected or not enough evidence will be available for network forensic analysis after security incidents occur."
        Remediation = "Navigate to Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\Logon/Logoff\Audit Group Membership and set it to include Success."
    },
    @{
        Id = "17.5.3"
        Title = "Ensure 'Audit Logoff' is set to include 'Success'"
        Section = "17.5 Logon/Logoff"
        Profile = "Level1"
        Type = "AuditPolicy"
        Subcategory = "Logoff"
        Expected = "Success"
        Description = "This policy setting allows you to audit when a user logs off from the computer. Events in this subcategory are generated on the computer that was accessed."
        Impact = "If no audit settings are configured, or if audit settings are too lax on the computers in your organization, security incidents might not be detected or not enough evidence will be available for network forensic analysis after security incidents occur."
        Remediation = "Navigate to Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\Logon/Logoff\Audit Logoff and set it to include Success."
    },
    @{
        Id = "17.5.4"
        Title = "Ensure 'Audit Logon' is set to 'Success and Failure'"
        Section = "17.5 Logon/Logoff"
        Profile = "Level1"
        Type = "AuditPolicy"
        Subcategory = "Logon"
        Expected = "Success and Failure"
        Description = "This policy setting allows you to audit each instance of a user logging on to or logging off from another computer in which this computer is used to validate the account."
        Impact = "If no audit settings are configured, or if audit settings are too lax on the computers in your organization, security incidents might not be detected or not enough evidence will be available for network forensic analysis after security incidents occur."
        Remediation = "Navigate to Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\Logon/Logoff\Audit Logon and set it to Success and Failure."
    },
    @{
        Id = "17.5.5"
        Title = "Ensure 'Audit Other Logon/Logoff Events' is set to 'Success and Failure'"
        Section = "17.5 Logon/Logoff"
        Profile = "Level1"
        Type = "AuditPolicy"
        Subcategory = "Other Logon/Logoff Events"
        Expected = "Success and Failure"
        Description = "This policy setting allows you to audit other logon/logoff-related events, such as Remote Desktop Services session disconnections and reconnections, using RunAs, and locking and unlocking a workstation."
        Impact = "If no audit settings are configured, or if audit settings are too lax on the computers in your organization, security incidents might not be detected or not enough evidence will be available for network forensic analysis after security incidents occur."
        Remediation = "Navigate to Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\Logon/Logoff\Audit Other Logon/Logoff Events and set it to Success and Failure."
    },
    @{
        Id = "17.5.6"
        Title = "Ensure 'Audit Special Logon' is set to include 'Success'"
        Section = "17.5 Logon/Logoff"
        Profile = "Level1"
        Type = "AuditPolicy"
        Subcategory = "Special Logon"
        Expected = "Success"
        Description = "This policy setting allows you to audit events generated by special logons such as the following: The use of a special logon, which is a logon that has administrator-equivalent privileges and can be used to elevate a process to a higher level; A logon by a member of a Special Group."
        Impact = "If no audit settings are configured, or if audit settings are too lax on the computers in your organization, security incidents might not be detected or not enough evidence will be available for network forensic analysis after security incidents occur."
        Remediation = "Navigate to Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\Logon/Logoff\Audit Special Logon and set it to include Success."
    },
    
    # 17.6 Object Access
    @{
        Id = "17.6.1"
        Title = "Ensure 'Audit Detailed File Share' is set to include 'Failure'"
        Section = "17.6 Object Access"
        Profile = "Level1"
        Type = "AuditPolicy"
        Subcategory = "Detailed File Share"
        Expected = "Failure"
        Description = "This policy setting allows you to audit attempts to access files and folders on a shared folder."
        Impact = "If no audit settings are configured, or if audit settings are too lax on the computers in your organization, security incidents might not be detected or not enough evidence will be available for network forensic analysis after security incidents occur."
        Remediation = "Navigate to Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\Object Access\Audit Detailed File Share and set it to include Failure."
    },
    @{
        Id = "17.6.2"
        Title = "Ensure 'Audit File Share' is set to 'Success and Failure'"
        Section = "17.6 Object Access"
        Profile = "Level1"
        Type = "AuditPolicy"
        Subcategory = "File Share"
        Expected = "Success and Failure"
        Description = "This policy setting allows you to audit attempts to access a shared folder."
        Impact = "If no audit settings are configured, or if audit settings are too lax on the computers in your organization, security incidents might not be detected or not enough evidence will be available for network forensic analysis after security incidents occur."
        Remediation = "Navigate to Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\Object Access\Audit File Share and set it to Success and Failure."
    },
    @{
        Id = "17.6.3"
        Title = "Ensure 'Audit Other Object Access Events' is set to 'Success and Failure'"
        Section = "17.6 Object Access"
        Profile = "Level1"
        Type = "AuditPolicy"
        Subcategory = "Other Object Access Events"
        Expected = "Success and Failure"
        Description = "This policy setting allows you to audit events generated by the management of task scheduler jobs or COM+ objects."
        Impact = "If no audit settings are configured, or if audit settings are too lax on the computers in your organization, security incidents might not be detected or not enough evidence will be available for network forensic analysis after security incidents occur."
        Remediation = "Navigate to Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\Object Access\Audit Other Object Access Events and set it to Success and Failure."
    },
    @{
        Id = "17.6.4"
        Title = "Ensure 'Audit Removable Storage' is set to 'Success and Failure'"
        Section = "17.6 Object Access"
        Profile = "Level1"
        Type = "AuditPolicy"
        Subcategory = "Removable Storage"
        Expected = "Success and Failure"
        Description = "This policy setting allows you to audit user attempts to access file system objects on a removable storage device."
        Impact = "If no audit settings are configured, or if audit settings are too lax on the computers in your organization, security incidents might not be detected or not enough evidence will be available for network forensic analysis after security incidents occur."
        Remediation = "Navigate to Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\Object Access\Audit Removable Storage and set it to Success and Failure."
    },
    
    # 17.7 Policy Change
    @{
        Id = "17.7.1"
        Title = "Ensure 'Audit Audit Policy Change' is set to include 'Success'"
        Section = "17.7 Policy Change"
        Profile = "Level1"
        Type = "AuditPolicy"
        Subcategory = "Audit Policy Change"
        Expected = "Success"
        Description = "This policy setting allows you to audit changes to the audit policy settings including the following: Changes to audit policy settings; Changes to resource attributes; Changes to Central Access Policies; Changes to per-user audit policy settings."
        Impact = "If no audit settings are configured, or if audit settings are too lax on the computers in your organization, security incidents might not be detected or not enough evidence will be available for network forensic analysis after security incidents occur."
        Remediation = "Navigate to Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\Policy Change\Audit Audit Policy Change and set it to include Success."
    },
    @{
        Id = "17.7.2"
        Title = "Ensure 'Audit Authentication Policy Change' is set to include 'Success'"
        Section = "17.7 Policy Change"
        Profile = "Level1"
        Type = "AuditPolicy"
        Subcategory = "Authentication Policy Change"
        Expected = "Success"
        Description = "This policy setting allows you to audit events generated by changes to the authentication policy including the following: Creation of forest and domain trusts; Modification of forest and domain trusts; Removal of forest and domain trusts; Changes to the Kerberos policy; Changes to the Password policy; Changes to the Account Lockout policy."
        Impact = "If no audit settings are configured, or if audit settings are too lax on the computers in your organization, security incidents might not be detected or not enough evidence will be available for network forensic analysis after security incidents occur."
        Remediation = "Navigate to Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\Policy Change\Audit Authentication Policy Change and set it to include Success."
    },
    @{
        Id = "17.7.3"
        Title = "Ensure 'Audit Authorization Policy Change' is set to include 'Success'"
        Section = "17.7 Policy Change"
        Profile = "Level1"
        Type = "AuditPolicy"
        Subcategory = "Authorization Policy Change"
        Expected = "Success"
        Description = "This policy setting allows you to audit events generated by changes to the authorization policy including the following: Changes to User Rights Assignment policy; Changes to Windows Firewall policy; Changes to SACL; Changes to Windows Trust Label policy."
        Impact = "If no audit settings are configured, or if audit settings are too lax on the computers in your organization, security incidents might not be detected or not enough evidence will be available for network forensic analysis after security incidents occur."
        Remediation = "Navigate to Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\Policy Change\Audit Authorization Policy Change and set it to include Success."
    },
    @{
        Id = "17.7.4"
        Title = "Ensure 'Audit MPSSVC Rule-Level Policy Change' is set to 'Success and Failure'"
        Section = "17.7 Policy Change"
        Profile = "Level1"
        Type = "AuditPolicy"
        Subcategory = "MPSSVC Rule-Level Policy Change"
        Expected = "Success and Failure"
        Description = "This policy setting allows you to audit events generated by changes in policy rules used by the Microsoft Protection Service (MPSSVC.exe)."
        Impact = "If no audit settings are configured, or if audit settings are too lax on the computers in your organization, security incidents might not be detected or not enough evidence will be available for network forensic analysis after security incidents occur."
        Remediation = "Navigate to Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\Policy Change\Audit MPSSVC Rule-Level Policy Change and set it to Success and Failure."
    },
    @{
        Id = "17.7.5"
        Title = "Ensure 'Audit Other Policy Change Events' is set to include 'Failure'"
        Section = "17.7 Policy Change"
        Profile = "Level1"
        Type = "AuditPolicy"
        Subcategory = "Other Policy Change Events"
        Expected = "Failure"
        Description = "This policy setting allows you to audit other security policy changes that are not audited in the Policy Change category such as changes to Trusted Platform Module (TPM) configuration and Kernel-mode cryptographic self tests."
        Impact = "If no audit settings are configured, or if audit settings are too lax on the computers in your organization, security incidents might not be detected or not enough evidence will be available for network forensic analysis after security incidents occur."
        Remediation = "Navigate to Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\Policy Change\Audit Other Policy Change Events and set it to include Failure."
    },
    
    # 17.8 Privilege Use
    @{
        Id = "17.8.1"
        Title = "Ensure 'Audit Sensitive Privilege Use' is set to 'Success and Failure'"
        Section = "17.8 Privilege Use"
        Profile = "Level1"
        Type = "AuditPolicy"
        Subcategory = "Sensitive Privilege Use"
        Expected = "Success and Failure"
        Description = "This policy setting allows you to audit events generated when sensitive privileges (user rights) are used. Sensitive privileges include the following user rights: Act as part of the operating system; Back up files and directories; Create a token object; Debug programs; Enable computer and user accounts to be trusted for delegation; Generate security audits; Impersonate a client after authentication; Load and unload device drivers; Manage auditing and security log; Modify firmware environment values; Replace a process-level token; Restore files and directories; Take ownership of files or other objects."
        Impact = "If no audit settings are configured, or if audit settings are too lax on the computers in your organization, security incidents might not be detected or not enough evidence will be available for network forensic analysis after security incidents occur."
        Remediation = "Navigate to Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\Privilege Use\Audit Sensitive Privilege Use and set it to Success and Failure."
    },
    
    # 17.9 System
    @{
        Id = "17.9.1"
        Title = "Ensure 'Audit IPsec Driver' is set to 'Success and Failure'"
        Section = "17.9 System"
        Profile = "Level1"
        Type = "AuditPolicy"
        Subcategory = "IPsec Driver"
        Expected = "Success and Failure"
        Description = "This policy setting allows you to audit events generated by the Internet Protocol security (IPsec) driver."
        Impact = "If no audit settings are configured, or if audit settings are too lax on the computers in your organization, security incidents might not be detected or not enough evidence will be available for network forensic analysis after security incidents occur."
        Remediation = "Navigate to Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\System\Audit IPsec Driver and set it to Success and Failure."
    },
    @{
        Id = "17.9.2"
        Title = "Ensure 'Audit Other System Events' is set to 'Success and Failure'"
        Section = "17.9 System"
        Profile = "Level1"
        Type = "AuditPolicy"
        Subcategory = "Other System Events"
        Expected = "Success and Failure"
        Description = "This policy setting allows you to audit other system events including startup and shutdown of the Windows Firewall service and driver, security policy processing by the Windows Firewall service, and cryptography key file and migration operations."
        Impact = "If no audit settings are configured, or if audit settings are too lax on the computers in your organization, security incidents might not be detected or not enough evidence will be available for network forensic analysis after security incidents occur."
        Remediation = "Navigate to Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\System\Audit Other System Events and set it to Success and Failure."
    },
    @{
        Id = "17.9.3"
        Title = "Ensure 'Audit Security State Change' is set to include 'Success'"
        Section = "17.9 System"
        Profile = "Level1"
        Type = "AuditPolicy"
        Subcategory = "Security State Change"
        Expected = "Success"
        Description = "This policy setting allows you to audit events generated by changes in the security state of the system, such as when the security subsystem starts and stops."
        Impact = "If no audit settings are configured, or if audit settings are too lax on the computers in your organization, security incidents might not be detected or not enough evidence will be available for network forensic analysis after security incidents occur."
        Remediation = "Navigate to Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\System\Audit Security State Change and set it to include Success."
    },
    @{
        Id = "17.9.4"
        Title = "Ensure 'Audit Security System Extension' is set to include 'Success'"
        Section = "17.9 System"
        Profile = "Level1"
        Type = "AuditPolicy"
        Subcategory = "Security System Extension"
        Expected = "Success"
        Description = "This policy setting allows you to audit events related to security system extensions or services. Examples include the following: A security system extension, such as an authentication, notification, or security package, is loaded and registered with the Local Security Authority (LSA); A service is installed and registered with the Service Control Manager."
        Impact = "If no audit settings are configured, or if audit settings are too lax on the computers in your organization, security incidents might not be detected or not enough evidence will be available for network forensic analysis after security incidents occur."
        Remediation = "Navigate to Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\System\Audit Security System Extension and set it to include Success."
    },
    @{
        Id = "17.9.5"
        Title = "Ensure 'Audit System Integrity' is set to 'Success and Failure'"
        Section = "17.9 System"
        Profile = "Level1"
        Type = "AuditPolicy"
        Subcategory = "System Integrity"
        Expected = "Success and Failure"
        Description = "This policy setting allows you to audit events that violate the integrity of the security subsystem."
        Impact = "If no audit settings are configured, or if audit settings are too lax on the computers in your organization, security incidents might not be detected or not enough evidence will be available for network forensic analysis after security incidents occur."
        Remediation = "Navigate to Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\System\Audit System Integrity and set it to Success and Failure."
    }
)