# Section 9: Windows Defender Firewall (Windows Server 2025)
$Global:Rules += @(
  # 9.2 Private Profile
  @{ Id='9.2.1'; Title='(L1) Ensure ''Windows Firewall: Private: Firewall state'' is set to ''On'''; Section='9.2 Private Profile'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PrivateProfile'; ValueName='EnableFirewall'; Expected=1; Description='Enables Private profile firewall'; Impact='Protects private networks'; Remediation='Enable Private firewall' },
  @{ Id='9.2.2'; Title='(L1) Ensure ''Windows Firewall: Private: Inbound connections'' is set to ''Block'''; Section='9.2 Private Profile'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PrivateProfile'; ValueName='DefaultInboundAction'; Expected=1; Description='Blocks inbound connections'; Impact='Prevents unauthorized access'; Remediation='Block Private inbound connections' },
  @{ Id='9.2.3'; Title='(L1) Ensure ''Windows Firewall: Private: Settings: Display a notification'' is set to ''No'''; Section='9.2 Private Profile'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PrivateProfile'; ValueName='DisableNotifications'; Expected=1; Description='Disables firewall notifications'; Impact='Reduces user interruptions'; Remediation='Disable Private firewall notifications' },
  @{ Id='9.2.4'; Title='(L1) Ensure ''Windows Firewall: Private: Logging: Name'' is configured'; Section='9.2 Private Profile'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging'; ValueName='LogFilePath'; Expected='%SystemRoot%\System32\logfiles\firewall\privatefw.log'; Description='Sets Private firewall log path'; Impact='Enables firewall logging'; Remediation='Configure Private firewall log path' },
  @{ Id='9.2.5'; Title='(L1) Ensure ''Windows Firewall: Private: Logging: Size limit (KB)'' is set to ''16,384 or greater'''; Section='9.2 Private Profile'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging'; ValueName='LogFileSize'; Expected=16384; Description='Sets Private firewall log size'; Impact='Ensures adequate logging'; Remediation='Set Private firewall log size to 16384 KB' },
  @{ Id='9.2.6'; Title='(L1) Ensure ''Windows Firewall: Private: Logging: Log dropped packets'' is set to ''Yes'''; Section='9.2 Private Profile'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging'; ValueName='LogDroppedPackets'; Expected=1; Description='Logs dropped packets'; Impact='Improves security monitoring'; Remediation='Enable Private firewall dropped packet logging' },
  @{ Id='9.2.7'; Title='(L1) Ensure ''Windows Firewall: Private: Logging: Log successful connections'' is set to ''Yes'''; Section='9.2 Private Profile'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging'; ValueName='LogSuccessfulConnections'; Expected=1; Description='Logs successful connections'; Impact='Improves security monitoring'; Remediation='Enable Private firewall connection logging' },
  
  # 9.3 Public Profile
  @{ Id='9.3.1'; Title='(L1) Ensure ''Windows Firewall: Public: Firewall state'' is set to ''On'''; Section='9.3 Public Profile'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PublicProfile'; ValueName='EnableFirewall'; Expected=1; Description='Enables Public profile firewall'; Impact='Protects public networks'; Remediation='Enable Public firewall' },
  @{ Id='9.3.2'; Title='(L1) Ensure ''Windows Firewall: Public: Inbound connections'' is set to ''Block'''; Section='9.3 Public Profile'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PublicProfile'; ValueName='DefaultInboundAction'; Expected=1; Description='Blocks inbound connections'; Impact='Prevents unauthorized access'; Remediation='Block Public inbound connections' },
  @{ Id='9.3.3'; Title='(L1) Ensure ''Windows Firewall: Public: Settings: Display a notification'' is set to ''No'''; Section='9.3 Public Profile'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PublicProfile'; ValueName='DisableNotifications'; Expected=1; Description='Disables firewall notifications'; Impact='Reduces user interruptions'; Remediation='Disable Public firewall notifications' },
  @{ Id='9.3.4'; Title='(L1) Ensure ''Windows Firewall: Public: Logging: Name'' is configured'; Section='9.3 Public Profile'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PublicProfile\Logging'; ValueName='LogFilePath'; Expected='%SystemRoot%\System32\logfiles\firewall\publicfw.log'; Description='Sets Public firewall log path'; Impact='Enables firewall logging'; Remediation='Configure Public firewall log path' },
  @{ Id='9.3.5'; Title='(L1) Ensure ''Windows Firewall: Public: Logging: Size limit (KB)'' is set to ''16,384 or greater'''; Section='9.3 Public Profile'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PublicProfile\Logging'; ValueName='LogFileSize'; Expected=16384; Description='Sets Public firewall log size'; Impact='Ensures adequate logging'; Remediation='Set Public firewall log size to 16384 KB' },
  @{ Id='9.3.6'; Title='(L1) Ensure ''Windows Firewall: Public: Logging: Log dropped packets'' is set to ''Yes'''; Section='9.3 Public Profile'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PublicProfile\Logging'; ValueName='LogDroppedPackets'; Expected=1; Description='Logs dropped packets'; Impact='Improves security monitoring'; Remediation='Enable Public firewall dropped packet logging' },
  @{ Id='9.3.7'; Title='(L1) Ensure ''Windows Firewall: Public: Logging: Log successful connections'' is set to ''Yes'''; Section='9.3 Public Profile'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PublicProfile\Logging'; ValueName='LogSuccessfulConnections'; Expected=1; Description='Logs successful connections'; Impact='Improves security monitoring'; Remediation='Enable Public firewall connection logging' }
)