# Extended Security Options (Windows Server 2025)
$Global:Rules += @(
  # 2.3.8 Microsoft network client
  @{ Id='2.3.8.1'; Title='(L1) Microsoft network client: Digitally sign communications (always)'; Section='2.3.8 Microsoft network client'; Profile='Level1'; Type='Registry'; Key='HKLM:\SYSTEM\CurrentControlSet\Services\lanmanserver\parameters'; ValueName='RequireSecuritySignature'; Expected=1; Description='Requires SMB client signing'; Impact='Prevents SMB attacks'; Remediation='Enable SMB client signing' },
  @{ Id='2.3.8.2'; Title='(L1) Microsoft network client: Digitally sign communications (if server agrees)'; Section='2.3.8 Microsoft network client'; Profile='Level1'; Type='Registry'; Key='HKLM:\SYSTEM\CurrentControlSet\Services\lanmanserver\parameters'; ValueName='EnableSecuritySignature'; Expected=1; Description='Enables SMB client signing negotiation'; Impact='Improves SMB security'; Remediation='Enable SMB client signing negotiation' },
  @{ Id='2.3.8.3'; Title='(L1) Microsoft network client: Send unencrypted password to third-party SMB servers'; Section='2.3.8 Microsoft network client'; Profile='Level1'; Type='Registry'; Key='HKLM:\SYSTEM\CurrentControlSet\Services\lanmanworkstation\parameters'; ValueName='EnablePlainTextPassword'; Expected=0; Description='Prevents plaintext passwords'; Impact='Protects credentials'; Remediation='Disable plaintext passwords' },
  
  # 2.3.9 Microsoft network server
  @{ Id='2.3.9.1'; Title='(L1) Microsoft network server: Amount of idle time before suspending session'; Section='2.3.9 Microsoft network server'; Profile='Level1'; Type='Registry'; Key='HKLM:\SYSTEM\CurrentControlSet\Services\lanmanserver\parameters'; ValueName='autodisconnect'; Expected=15; Description='Sets SMB session timeout'; Impact='Reduces idle session exposure'; Remediation='Set SMB timeout to 15 minutes' },
  @{ Id='2.3.9.2'; Title='(L1) Microsoft network server: Digitally sign communications (always)'; Section='2.3.9 Microsoft network server'; Profile='Level1'; Type='Registry'; Key='HKLM:\SYSTEM\CurrentControlSet\Services\lanmanserver\parameters'; ValueName='RequireSecuritySignature'; Expected=1; Description='Requires SMB server signing'; Impact='Prevents SMB attacks'; Remediation='Enable SMB server signing' },
  @{ Id='2.3.9.3'; Title='(L1) Microsoft network server: Digitally sign communications (if client agrees)'; Section='2.3.9 Microsoft network server'; Profile='Level1'; Type='Registry'; Key='HKLM:\SYSTEM\CurrentControlSet\Services\lanmanserver\parameters'; ValueName='EnableSecuritySignature'; Expected=1; Description='Enables SMB server signing'; Impact='Improves SMB security'; Remediation='Enable SMB server signing negotiation' },
  
  # 2.3.10 Network access
  @{ Id='2.3.10.1'; Title='(L1) Network access: Allow anonymous SID/Name translation'; Section='2.3.10 Network access'; Profile='Level1'; Type='Registry'; Key='HKLM:\SYSTEM\CurrentControlSet\Control\Lsa'; ValueName='TurnOffAnonymousBlock'; Expected=1; Description='Prevents anonymous SID enumeration'; Impact='Reduces information disclosure'; Remediation='Disable anonymous SID translation' },
  @{ Id='2.3.10.2'; Title='(L1) Network access: Do not allow anonymous enumeration of SAM accounts'; Section='2.3.10 Network access'; Profile='Level1'; Type='Registry'; Key='HKLM:\SYSTEM\CurrentControlSet\Control\Lsa'; ValueName='RestrictAnonymousSAM'; Expected=1; Description='Prevents SAM enumeration'; Impact='Protects account information'; Remediation='Enable SAM restriction' },
  @{ Id='2.3.10.3'; Title='(L1) Network access: Do not allow anonymous enumeration of SAM accounts and shares'; Section='2.3.10 Network access'; Profile='Level1'; Type='Registry'; Key='HKLM:\SYSTEM\CurrentControlSet\Control\Lsa'; ValueName='RestrictAnonymous'; Expected=1; Description='Prevents anonymous enumeration'; Impact='Reduces information disclosure'; Remediation='Enable anonymous restriction' },
  
  # 2.3.11 Network security
  @{ Id='2.3.11.1'; Title='(L1) Network security: Allow Local System to use computer identity for NTLM'; Section='2.3.11 Network security'; Profile='Level1'; Type='Registry'; Key='HKLM:\SYSTEM\CurrentControlSet\Control\Lsa'; ValueName='UseMachineId'; Expected=1; Description='Uses machine identity for NTLM'; Impact='Improves authentication'; Remediation='Enable machine identity' },
  @{ Id='2.3.11.2'; Title='(L1) Network security: Allow LocalSystem NULL session fallback'; Section='2.3.11 Network security'; Profile='Level1'; Type='Registry'; Key='HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0'; ValueName='AllowNullSessionFallback'; Expected=0; Description='Prevents NULL session fallback'; Impact='Improves authentication'; Remediation='Disable NULL session fallback' },
  @{ Id='2.3.11.3'; Title='(L1) Network security: Do not store LAN Manager hash value'; Section='2.3.11 Network security'; Profile='Level1'; Type='Registry'; Key='HKLM:\SYSTEM\CurrentControlSet\Control\Lsa'; ValueName='NoLMHash'; Expected=1; Description='Prevents LM hash storage'; Impact='Improves password security'; Remediation='Disable LM hash storage' },
  @{ Id='2.3.11.4'; Title='(L1) Network security: LAN Manager authentication level'; Section='2.3.11 Network security'; Profile='Level1'; Type='Registry'; Key='HKLM:\SYSTEM\CurrentControlSet\Control\Lsa'; ValueName='LmCompatibilityLevel'; Expected=5; Description='Sets NTLM authentication level'; Impact='Improves authentication security'; Remediation='Set LM compatibility to level 5' },
  
  # 2.3.17 User Account Control
  @{ Id='2.3.17.1'; Title='(L1) User Account Control: Admin Approval Mode for Built-in Administrator'; Section='2.3.17 User Account Control'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'; ValueName='FilterAdministratorToken'; Expected=1; Description='Enables UAC for Administrator'; Impact='Improves security'; Remediation='Enable UAC for Administrator' },
  @{ Id='2.3.17.2'; Title='(L1) User Account Control: Behavior of elevation prompt for administrators'; Section='2.3.17 User Account Control'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'; ValueName='ConsentPromptBehaviorAdmin'; Expected=2; Description='Sets UAC admin prompt'; Impact='Controls elevation'; Remediation='Configure UAC admin prompt' },
  @{ Id='2.3.17.3'; Title='(L1) User Account Control: Behavior of elevation prompt for standard users'; Section='2.3.17 User Account Control'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'; ValueName='ConsentPromptBehaviorUser'; Expected=0; Description='Denies user elevation'; Impact='Prevents unauthorized elevation'; Remediation='Deny user elevation' },
  @{ Id='2.3.17.4'; Title='(L1) User Account Control: Detect application installations'; Section='2.3.17 User Account Control'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'; ValueName='EnableInstallerDetection'; Expected=1; Description='Detects installers'; Impact='Prevents unauthorized installs'; Remediation='Enable installer detection' },
  @{ Id='2.3.17.5'; Title='(L1) User Account Control: Only elevate UIAccess applications in secure locations'; Section='2.3.17 User Account Control'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'; ValueName='EnableSecureUIAPaths'; Expected=1; Description='Restricts UIAccess'; Impact='Prevents malicious elevation'; Remediation='Enable secure UIAccess' },
  @{ Id='2.3.17.6'; Title='(L1) User Account Control: Run all administrators in Admin Approval Mode'; Section='2.3.17 User Account Control'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'; ValueName='EnableLUA'; Expected=1; Description='Enables UAC'; Impact='Improves security'; Remediation='Enable UAC' },
  @{ Id='2.3.17.7'; Title='(L1) User Account Control: Switch to secure desktop when prompting'; Section='2.3.17 User Account Control'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'; ValueName='PromptOnSecureDesktop'; Expected=1; Description='Uses secure desktop'; Impact='Prevents UAC bypass'; Remediation='Enable secure desktop' },
  @{ Id='2.3.17.8'; Title='(L1) User Account Control: Virtualize file and registry write failures'; Section='2.3.17 User Account Control'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'; ValueName='EnableVirtualization'; Expected=1; Description='Enables virtualization'; Impact='Improves compatibility'; Remediation='Enable virtualization' }
)