# Extended Administrative Templates (Windows Server 2025)
$Global:Rules += @(
  # 18.6 Network
  @{ Id='18.6.4.1'; Title='(L1) Configure multicast DNS (mDNS) protocol'; Section='18.6.4 DNS Client'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient'; ValueName='EnableMulticast'; Expected=0; Description='Disables mDNS protocol'; Impact='Reduces attack surface'; Remediation='Disable mDNS' },
  @{ Id='18.6.7.1'; Title='(L1) Audit client does not support encryption'; Section='18.6.7 Lanman Server'; Profile='Level1'; Type='Registry'; Key='HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters'; ValueName='AuditBaseObjects'; Expected=1; Description='Audits SMB encryption'; Impact='Improves monitoring'; Remediation='Enable SMB encryption audit' },
  @{ Id='18.6.8.1'; Title='(L1) Audit insecure guest logon'; Section='18.6.8 Lanman Workstation'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\Windows\LanmanWorkstation'; ValueName='AllowInsecureGuestAuth'; Expected=0; Description='Prevents insecure guest logon'; Impact='Improves SMB security'; Remediation='Disable insecure guest auth' },
  
  # 18.7 Printers
  @{ Id='18.7.1'; Title='(L1) Allow Print Spooler to accept client connections'; Section='18.7 Printers'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Printers'; ValueName='RegisterSpoolerRemoteRpcEndPoint'; Expected=2; Description='Controls print spooler connections'; Impact='Prevents PrintNightmare'; Remediation='Disable spooler remote connections' },
  @{ Id='18.7.2'; Title='(L1) Configure Redirection Guard'; Section='18.7 Printers'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Printers'; ValueName='RedirectionguardPolicy'; Expected=1; Description='Enables redirection guard'; Impact='Prevents print redirection attacks'; Remediation='Enable redirection guard' },
  @{ Id='18.7.3'; Title='(L1) Configure RPC connection settings: Protocol to use for outgoing RPC'; Section='18.7 Printers'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Printers\RPC'; ValueName='RpcProtocols'; Expected=5; Description='Sets RPC protocol'; Impact='Improves RPC security'; Remediation='Use RPC over TCP' },
  
  # 18.9 System
  @{ Id='18.9.3.1'; Title='(L1) Include command line in process creation events'; Section='18.9.3 Audit Process Creation'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Audit'; ValueName='ProcessCreationIncludeCmdLine_Enabled'; Expected=1; Description='Includes command line in audit'; Impact='Improves forensics'; Remediation='Enable command line auditing' },
  @{ Id='18.9.4.1'; Title='(L1) Encryption Oracle Remediation'; Section='18.9.4 Credentials Delegation'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\CredSSP\Parameters'; ValueName='AllowEncryptionOracle'; Expected=0; Description='Prevents CredSSP oracle'; Impact='Prevents credential theft'; Remediation='Disable encryption oracle' },
  @{ Id='18.9.13.1'; Title='(L1) Boot-Start Driver Initialization Policy'; Section='18.9.13 Early Launch Antimalware'; Profile='Level1'; Type='Registry'; Key='HKLM:\SYSTEM\CurrentControlSet\Policies\EarlyLaunch'; ValueName='DriverLoadPolicy'; Expected=3; Description='Controls driver loading'; Impact='Prevents malicious drivers'; Remediation='Set driver policy to good/unknown/bad critical' },
  
  # 18.10 Windows Components
  @{ Id='18.10.8.1'; Title='(L1) Disallow Autoplay for non-volume devices'; Section='18.10.8 AutoPlay Policies'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\Windows\Explorer'; ValueName='NoAutoplayfornonVolume'; Expected=1; Description='Disables autoplay for devices'; Impact='Prevents malware execution'; Remediation='Disable device autoplay' },
  @{ Id='18.10.8.2'; Title='(L1) Set the default behavior for AutoRun'; Section='18.10.8 AutoPlay Policies'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer'; ValueName='NoAutorun'; Expected=1; Description='Disables autorun'; Impact='Prevents malware execution'; Remediation='Disable autorun' },
  @{ Id='18.10.8.3'; Title='(L1) Turn off Autoplay'; Section='18.10.8 AutoPlay Policies'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer'; ValueName='NoDriveTypeAutoRun'; Expected=255; Description='Disables autoplay for all drives'; Impact='Prevents malware execution'; Remediation='Disable autoplay for all drives' },
  
  # 18.10.43 Microsoft Defender Antivirus
  @{ Id='18.10.43.4.1'; Title='(L1) Enable EDR in block mode'; Section='18.10.43.4 Features'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\Windows Advanced Threat Protection'; ValueName='ForceDefenderPassiveMode'; Expected=0; Description='Enables EDR block mode'; Impact='Improves threat detection'; Remediation='Enable EDR block mode' },
  @{ Id='18.10.43.5.1'; Title='(L1) Configure local setting override for reporting to Microsoft MAPS'; Section='18.10.43.5 MAPS'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Spynet'; ValueName='LocalSettingOverrideSpynetReporting'; Expected=0; Description='Prevents MAPS override'; Impact='Maintains security policy'; Remediation='Disable MAPS override' },
  @{ Id='18.10.43.6.1.1'; Title='(L1) Configure Attack Surface Reduction rules'; Section='18.10.43.6.1 Attack Surface Reduction'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR'; ValueName='ExploitGuard_ASR_Rules'; Expected=1; Description='Enables ASR rules'; Impact='Reduces attack surface'; Remediation='Enable ASR rules' },
  @{ Id='18.10.43.10.1'; Title='(L1) Configure real-time protection and Security Intelligence Updates during OOBE'; Section='18.10.43.10 Real-time Protection'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection'; ValueName='RealtimeScanDirection'; Expected=0; Description='Configures real-time protection'; Impact='Improves malware detection'; Remediation='Configure real-time protection' },
  @{ Id='18.10.43.10.2'; Title='(L1) Scan all downloaded files and attachments'; Section='18.10.43.10 Real-time Protection'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection'; ValueName='DisableIOAVProtection'; Expected=0; Description='Scans downloaded files'; Impact='Prevents malware execution'; Remediation='Enable download scanning' },
  @{ Id='18.10.43.10.3'; Title='(L1) Turn off real-time protection'; Section='18.10.43.10 Real-time Protection'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection'; ValueName='DisableRealtimeMonitoring'; Expected=0; Description='Enables real-time protection'; Impact='Improves malware detection'; Remediation='Enable real-time protection' },
  
  # 18.10.57 Remote Desktop Services
  @{ Id='18.10.57.2.2'; Title='(L1) Do not allow passwords to be saved'; Section='18.10.57.2 Remote Desktop Connection Client'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'; ValueName='DisablePasswordSaving'; Expected=1; Description='Prevents password saving'; Impact='Protects credentials'; Remediation='Disable RDP password saving' },
  @{ Id='18.10.57.3.9.1'; Title='(L1) Always prompt for password upon connection'; Section='18.10.57.3.9 Security'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'; ValueName='fPromptForPassword'; Expected=1; Description='Requires password prompt'; Impact='Improves authentication'; Remediation='Enable RDP password prompt' },
  @{ Id='18.10.57.3.9.2'; Title='(L1) Require secure RPC communication'; Section='18.10.57.3.9 Security'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'; ValueName='fEncryptRPCTraffic'; Expected=1; Description='Encrypts RPC traffic'; Impact='Protects RDP communications'; Remediation='Enable RPC encryption' },
  @{ Id='18.10.57.3.9.3'; Title='(L1) Require use of specific security layer for remote (RDP) connections'; Section='18.10.57.3.9 Security'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'; ValueName='SecurityLayer'; Expected=2; Description='Sets RDP security layer'; Impact='Improves RDP security'; Remediation='Use SSL for RDP' },
  
  # 18.10.89 Windows Remote Management (WinRM)
  @{ Id='18.10.89.1.1'; Title='(L1) Allow Basic authentication'; Section='18.10.89.1 WinRM Client'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\Windows\WinRM\Client'; ValueName='AllowBasic'; Expected=0; Description='Disables basic authentication'; Impact='Improves authentication security'; Remediation='Disable WinRM basic auth' },
  @{ Id='18.10.89.1.2'; Title='(L1) Allow unencrypted traffic'; Section='18.10.89.1 WinRM Client'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\Windows\WinRM\Client'; ValueName='AllowUnencryptedTraffic'; Expected=0; Description='Requires encrypted traffic'; Impact='Protects communications'; Remediation='Disable unencrypted WinRM' },
  @{ Id='18.10.89.2.1'; Title='(L1) Allow Basic authentication'; Section='18.10.89.2 WinRM Service'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\Windows\WinRM\Service'; ValueName='AllowBasic'; Expected=0; Description='Disables basic authentication'; Impact='Improves authentication security'; Remediation='Disable WinRM service basic auth' },
  
  # 18.10.93 Windows Update
  @{ Id='18.10.93.2.1'; Title='(L1) Configure Automatic Updates'; Section='18.10.93.2 Manage end user experience'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU'; ValueName='NoAutoUpdate'; Expected=0; Description='Enables automatic updates'; Impact='Improves security patching'; Remediation='Enable automatic updates' },
  @{ Id='18.10.93.4.1'; Title='(L1) Manage preview builds'; Section='18.10.93.4 Manage updates offered from Windows Update'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\Windows\PreviewBuilds'; ValueName='AllowBuildPreview'; Expected=0; Description='Disables preview builds'; Impact='Improves stability'; Remediation='Disable preview builds' },
  @{ Id='18.10.93.4.2'; Title='(L1) Select when Preview Builds and Feature Updates are received'; Section='18.10.93.4 Manage updates offered from Windows Update'; Profile='Level1'; Type='Registry'; Key='HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate'; ValueName='DeferFeatureUpdatesPeriodInDays'; Expected=180; Description='Defers feature updates'; Impact='Improves stability'; Remediation='Defer feature updates 180 days' }
)